// Autogenerated by Prisma Compact Compiler for Midnight Network
import type * as __compactRuntime from '@midnight-ntwrk/compact-runtime';

export type Witnesses<PS> = {
  get_accrued_balance(context: __compactRuntime.WitnessContext<PS>, stream_id: Uint8Array | string, current_time: bigint): bigint;
  get_worker_credential(context: __compactRuntime.WitnessContext<PS>, worker_sk: Uint8Array | string): Uint8Array | string;
  generate_withdrawal_nullifier(context: __compactRuntime.WitnessContext<PS>, stream_id: Uint8Array | string, nonce: bigint, worker_sk: Uint8Array | string): Uint8Array | string;
};

export type ImpureCircuits<PS> = {
  createStream(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, allocation_amount: bigint, employer_credential: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  withdrawSalary(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, withdraw_amount: bigint, nullifier: Uint8Array | string, worker_sk: Uint8Array | string, current_time: bigint, nonce: bigint): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type ProvableCircuits<PS> = {
  createStream(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, allocation_amount: bigint, employer_credential: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  withdrawSalary(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, withdraw_amount: bigint, nullifier: Uint8Array | string, worker_sk: Uint8Array | string, current_time: bigint, nonce: bigint): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type PureCircuits = {};

export type Circuits<PS> = {
  createStream(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, allocation_amount: bigint, employer_credential: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  withdrawSalary(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, withdraw_amount: bigint, nullifier: Uint8Array | string, worker_sk: Uint8Array | string, current_time: bigint, nonce: bigint): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type Ledger = {
  readonly total_payroll_budget: bigint;
  readonly total_disbursed: bigint;
  readonly employer_vk: Uint8Array | string;
  readonly last_nullifier: Uint8Array | string;
  readonly active_streams: bigint;
  readonly total_spent: bigint;
  readonly spending_limit: bigint;
};

export type ContractReferenceLocations = any;
export declare const contractReferenceLocations: ContractReferenceLocations;

export declare class Contract<PS = any, W extends Witnesses<PS> = Witnesses<PS>> {
  witnesses: W;
  circuits: Circuits<PS>;
  impureCircuits: ImpureCircuits<PS>;
  provableCircuits: ProvableCircuits<PS>;
  constructor(witnesses: W);
  initialState(context: __compactRuntime.ConstructorContext<PS>, ...args: any[]): __compactRuntime.ConstructorResult<PS>;
}

export declare function ledger(state: __compactRuntime.StateValue | __compactRuntime.ChargedState): Ledger;
export declare const pureCircuits: PureCircuits;
