// Autogenerated by Prisma Compact Compiler for Midnight Network
import type * as __compactRuntime from '@midnight-ntwrk/compact-runtime';

export type Witnesses<PS> = {
  verify_pool_signature(context: __compactRuntime.WitnessContext<PS>, pool_vk: Uint8Array | string, stream_id: Uint8Array | string, amount: bigint, pool_sig: Uint8Array | string): boolean;
  get_unaccrued_salary_collateral(context: __compactRuntime.WitnessContext<PS>, stream_id: Uint8Array | string, worker_sk: Uint8Array | string): bigint;
  is_advance_nullifier_consumed(context: __compactRuntime.WitnessContext<PS>, nullifier: Uint8Array | string): boolean;
  compute_advance_nullifier(context: __compactRuntime.WitnessContext<PS>, stream_id: Uint8Array | string, nonce: bigint, worker_sk: Uint8Array | string): Uint8Array | string;
};

export type ImpureCircuits<PS> = {
  disburseSalaryAdvance(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, requested_amount: bigint, advance_nonce: bigint, advance_nullifier: Uint8Array | string, pool_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type ProvableCircuits<PS> = {
  disburseSalaryAdvance(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, requested_amount: bigint, advance_nonce: bigint, advance_nullifier: Uint8Array | string, pool_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type PureCircuits = {};

export type Circuits<PS> = {
  disburseSalaryAdvance(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, requested_amount: bigint, advance_nonce: bigint, advance_nullifier: Uint8Array | string, pool_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type Ledger = {
  readonly pool_authority_vk: Uint8Array | string;
  readonly total_advances_disbursed: bigint;
  readonly total_fees_collected: bigint;
  readonly total_outstanding_principal: bigint;
  readonly total_advances_count: bigint;
};

export type ContractReferenceLocations = any;
export declare const contractReferenceLocations: ContractReferenceLocations;

export declare class Contract<PS = any, W extends Witnesses<PS> = Witnesses<PS>> {
  witnesses: W;
  circuits: Circuits<PS>;
  impureCircuits: ImpureCircuits<PS>;
  provableCircuits: ProvableCircuits<PS>;
  constructor(witnesses: W);
  initialState(context: __compactRuntime.ConstructorContext<PS>, ...args: any[]): __compactRuntime.ConstructorResult<PS>;
}

export declare function ledger(state: __compactRuntime.StateValue | __compactRuntime.ChargedState): Ledger;
export declare const pureCircuits: PureCircuits;
