// Autogenerated by Prisma Compact Compiler for Midnight Network
import type * as __compactRuntime from '@midnight-ntwrk/compact-runtime';

export type Witnesses<PS> = {
  get_confidential_tax_records(context: __compactRuntime.WitnessContext<PS>, worker_sk: Uint8Array | string, fiscal_year: bigint): bigint;
  compute_audit_attestation_digest(context: __compactRuntime.WitnessContext<PS>, fiscal_year: bigint, jurisdiction_id: Uint8Array | string, salt: Uint8Array | string): Uint8Array | string;
};

export type ImpureCircuits<PS> = {
  verifyTaxCompliance(context: __compactRuntime.CircuitContext<PS>, fiscal_year: bigint, jurisdiction_id: Uint8Array | string, bracket_min: bigint, bracket_max: bigint, withholding_paid: bigint, withholding_rate_bps: bigint, attestation_salt: Uint8Array | string, compliance_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type ProvableCircuits<PS> = {
  verifyTaxCompliance(context: __compactRuntime.CircuitContext<PS>, fiscal_year: bigint, jurisdiction_id: Uint8Array | string, bracket_min: bigint, bracket_max: bigint, withholding_paid: bigint, withholding_rate_bps: bigint, attestation_salt: Uint8Array | string, compliance_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type PureCircuits = {};

export type Circuits<PS> = {
  verifyTaxCompliance(context: __compactRuntime.CircuitContext<PS>, fiscal_year: bigint, jurisdiction_id: Uint8Array | string, bracket_min: bigint, bracket_max: bigint, withholding_paid: bigint, withholding_rate_bps: bigint, attestation_salt: Uint8Array | string, compliance_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type Ledger = {
  readonly compliance_authority_vk: Uint8Array | string;
  readonly last_attestation_id: Uint8Array | string;
  readonly total_compliance_proofs: bigint;
  readonly certified_tax_year: bigint;
};

export type ContractReferenceLocations = any;
export declare const contractReferenceLocations: ContractReferenceLocations;

export declare class Contract<PS = any, W extends Witnesses<PS> = Witnesses<PS>> {
  witnesses: W;
  circuits: Circuits<PS>;
  impureCircuits: ImpureCircuits<PS>;
  provableCircuits: ProvableCircuits<PS>;
  constructor(witnesses: W);
  initialState(context: __compactRuntime.ConstructorContext<PS>, ...args: any[]): __compactRuntime.ConstructorResult<PS>;
}

export declare function ledger(state: __compactRuntime.StateValue | __compactRuntime.ChargedState): Ledger;
export declare const pureCircuits: PureCircuits;
