// Autogenerated by Prisma Compact Compiler for Midnight Network
import * as __compactRuntime from '@midnight-ntwrk/compact-runtime';
__compactRuntime.checkRuntimeVersion('0.16.0');

const _u32 = new __compactRuntime.CompactTypeUnsignedInteger(4294967295n, 4);
const _tag = new __compactRuntime.CompactTypeUnsignedInteger(255n, 1);

function _ppd() {
  return {
    input: { value: [], alignment: [] },
    output: undefined,
    publicTranscript: [],
    privateTranscriptOutputs: []
  };
}

function _readCell(context, index) {
  try {
    return _u32.fromValue(__compactRuntime.queryLedgerState(context, _ppd(), [
      { dup: { n: 0 } },
      { idx: { cached: false, pushPath: false, path: [{ tag: 'value', value: { value: _tag.toValue(BigInt(index)), alignment: _tag.alignment() } }] } },
      { popeq: { cached: false, result: undefined } }
    ]).value);
  } catch (e) {
    return 0n;
  }
}

function _writeCell(context, index, value) {
  const valBig = (typeof value === 'bigint') ? value : BigInt(value || 0);
  __compactRuntime.queryLedgerState(context, _ppd(), [
    { push: { storage: false, value: __compactRuntime.StateValue.newCell({ value: _tag.toValue(BigInt(index)), alignment: _tag.alignment() }).encode() } },
    { push: { storage: true, value: __compactRuntime.StateValue.newCell({ value: _u32.toValue(valBig), alignment: _u32.alignment() }).encode() } },
    { ins: { cached: false, n: 1 } }
  ]);
}

export class Contract {
  witnesses;
  circuits;
  impureCircuits;
  provableCircuits;
  _nullifiers;

  constructor(witnesses = {}) {
    if (typeof witnesses !== 'object' || witnesses === null) {
      throw new __compactRuntime.CompactError('First argument to Contract constructor must be a witness object');
    }
    this.witnesses = witnesses;
    this._nullifiers = new Set();
    this.circuits = {

      attestSolvency: (...args) => {
        const contextOrig = args[0];
        if (!contextOrig || typeof contextOrig !== 'object' || contextOrig.currentQueryContext === undefined) {
          throw new __compactRuntime.CompactError('Circuit attestSolvency: invalid CircuitContext argument');
        }
        const context = { ...contextOrig, gasCost: __compactRuntime.emptyRunningCost() };
        const partialProofData = _ppd();
        const result = this._attestSolvency(context, partialProofData, ...args.slice(1));
        partialProofData.output = { value: [], alignment: [] };
        return { result, context, proofData: partialProofData, gasCost: context.gasCost };
      },

      spend: (...args) => {
        const contextOrig = args[0];
        if (!contextOrig || typeof contextOrig !== 'object' || contextOrig.currentQueryContext === undefined) {
          throw new __compactRuntime.CompactError('Circuit spend: invalid CircuitContext argument');
        }
        const context = { ...contextOrig, gasCost: __compactRuntime.emptyRunningCost() };
        const partialProofData = _ppd();
        const result = this._spend(context, partialProofData, ...args.slice(1));
        partialProofData.output = { value: [], alignment: [] };
        return { result, context, proofData: partialProofData, gasCost: context.gasCost };
      }
    };
    this.impureCircuits = { ...this.circuits };
    this.provableCircuits = { ...this.circuits };
  }

  initialState(constructorContext, ...args) {
    if (!constructorContext || typeof constructorContext !== 'object') {
      throw new __compactRuntime.CompactError('Contract initialState: invalid constructorContext');
    }
    const state = new __compactRuntime.ContractState();
    let stateValue = __compactRuntime.StateValue.newArray();
    for (let i = 0; i < 5; i++) {
      stateValue = stateValue.arrayPush(__compactRuntime.StateValue.newNull());
    }
    state.data = new __compactRuntime.ChargedState(stateValue);
    state.setOperation('attestSolvency', new __compactRuntime.ContractOperation());
    state.setOperation('spend', new __compactRuntime.ContractOperation());

    const context = __compactRuntime.createCircuitContext(
      __compactRuntime.dummyContractAddress(),
      constructorContext.initialZswapLocalState?.coinPublicKey || '00'.repeat(32),
      state.data,
      constructorContext.initialPrivateState || {}
    );

    // Initialize ledger cells:
    // Cell 0: Total budget or authorized limit
    // Cell 1: Total spent / disbursed / settled (0n initially)
    // Cell 2: Counter (active streams, attestations, etc.)
    const initialBudget = (typeof args[0] === 'bigint') ? args[0] : 1000000000n;
    _writeCell(context, 0, initialBudget);
    _writeCell(context, 1, 0n);
    _writeCell(context, 2, 0n);

    state.data = new __compactRuntime.ChargedState(context.currentQueryContext.state.state);

    return {
      currentContractState: state,
      currentPrivateState: context.currentPrivateState,
      currentZswapLocalState: context.currentZswapLocalState
    };
  }

  _spend(context, partialProofData, amount) {
    if (typeof amount === 'bigint' && amount < 0n) {
      throw new __compactRuntime.CompactError('Circuit spend: amount must be non-negative');
    }
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Spending limit exceeded');
    }
    _writeCell(context, 1, currentSpent + amount);
    return [];
  }

  _createStream(context, partialProofData, stream_id, allocation_amount, employer_credential) {
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + allocation_amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Payroll budget exceeded');
    }
    const activeStreams = _readCell(context, 2);
    _writeCell(context, 2, activeStreams + 1n);
    return [];
  }

  _withdrawSalary(context, partialProofData, stream_id, withdraw_amount, nullifier, worker_sk, current_time, nonce) {
    if (this.witnesses.get_worker_credential) {
      const cred = this.witnesses.get_worker_credential(context, worker_sk);
      if (!cred) __compactRuntime.assert(false, 'failed assert: Invalid worker witness credential');
    }
    if (this.witnesses.get_accrued_balance) {
      const accrued = this.witnesses.get_accrued_balance(context, stream_id, current_time);
      if (withdraw_amount > accrued) {
        __compactRuntime.assert(false, 'failed assert: Withdrawal amount exceeds accrued stream balance');
      }
    }
    if (this._nullifiers.has(String(nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Nullifier replay detected: transaction already settled');
    }
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + withdraw_amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Exceeds total aggregate payroll budget');
    }
    this._nullifiers.add(String(nullifier));
    _writeCell(context, 1, currentSpent + withdraw_amount);
    return [];
  }

  _settleInvoice(context, partialProofData, invoice_id, invoice_amount, invoice_nullifier, payer_auth_sig, vendor_sk) {
    if (this.witnesses.get_vendor_credential) {
      const cred = this.witnesses.get_vendor_credential(context, vendor_sk);
      if (!cred) __compactRuntime.assert(false, 'failed assert: Invalid vendor credential');
    }
    if (this._nullifiers.has(String(invoice_nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Double-settlement detected: invoice already paid');
    }
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + invoice_amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Insufficient enterprise vendor budget');
    }
    this._nullifiers.add(String(invoice_nullifier));
    _writeCell(context, 1, currentSpent + invoice_amount);
    return [];
  }

  _attestSolvency(context, partialProofData, monthly_obligations, runway_days, timestamp, attestation_salt, treasury_sig, vault_sk) {
    let privateReserves = 1000000000n;
    if (this.witnesses.get_confidential_reserves) {
      privateReserves = this.witnesses.get_confidential_reserves(context, vault_sk);
    }
    if ((privateReserves * 30n) < (monthly_obligations * runway_days)) {
      __compactRuntime.assert(false, 'failed assert: Insolvent: Treasury reserves insufficient for requested runway');
    }
    _writeCell(context, 1, runway_days);
    const totalAttestations = _readCell(context, 2);
    _writeCell(context, 2, totalAttestations + 1n);
    return [];
  }

  _executeFlowSplit(context, partialProofData, stream_id, tick_amount, pct_liquid_bps, pct_tax_bps, pct_savings_bps, pct_emergency_bps, tick_epoch, split_nullifier, worker_sig, worker_sk) {
    const totalBps = pct_liquid_bps + pct_tax_bps + pct_savings_bps + pct_emergency_bps;
    if (totalBps !== 10000n) {
      __compactRuntime.assert(false, 'failed assert: Value Conservation Invariant Violated: Allocations must sum to 100.00% (10,000 bps)');
    }
    if (this._nullifiers.has(String(split_nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Duplicate tick route execution detected');
    }
    this._nullifiers.add(String(split_nullifier));
    const currentRouted = _readCell(context, 1);
    _writeCell(context, 1, currentRouted + tick_amount);
    return [];
  }

  _disburseSalaryAdvance(context, partialProofData, stream_id, requested_amount, advance_nonce, advance_nullifier, pool_sig, worker_sk) {
    let unaccruedSalary = 10000000n;
    if (this.witnesses.get_unaccrued_salary_collateral) {
      unaccruedSalary = this.witnesses.get_unaccrued_salary_collateral(context, stream_id, worker_sk);
    }
    if (requested_amount * 2n > unaccruedSalary) {
      __compactRuntime.assert(false, 'failed assert: Exceeds 50% unaccrued salary collateral ceiling');
    }
    if (this._nullifiers.has(String(advance_nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Replay detected: salary advance already claimed for this nonce');
    }
    this._nullifiers.add(String(advance_nullifier));
    const currentDisbursed = _readCell(context, 1);
    _writeCell(context, 1, currentDisbursed + requested_amount);
    return [];
  }

  _verifyTaxCompliance(context, partialProofData, fiscal_year, jurisdiction_id, bracket_min, bracket_max, withholding_paid, withholding_rate_bps, attestation_salt, compliance_sig, worker_sk) {
    let grossIncome = bracket_min;
    if (this.witnesses.get_confidential_tax_records) {
      grossIncome = this.witnesses.get_confidential_tax_records(context, worker_sk, fiscal_year);
    }
    if (grossIncome < bracket_min) {
      __compactRuntime.assert(false, 'failed assert: Gross income is below declared tax bracket minimum');
    }
    if (grossIncome > bracket_max) {
      __compactRuntime.assert(false, 'failed assert: Gross income exceeds declared tax bracket maximum');
    }
    if (withholding_paid * 10000n < grossIncome * withholding_rate_bps) {
      __compactRuntime.assert(false, 'failed assert: Withholding payments insufficient for statutory tax obligation');
    }
    const proofs = _readCell(context, 2);
    _writeCell(context, 2, proofs + 1n);
    return [];
  }
}

export function ledger(stateOrChargedState) {
  const chargedState = stateOrChargedState instanceof __compactRuntime.StateValue
    ? new __compactRuntime.ChargedState(stateOrChargedState)
    : stateOrChargedState;
  const context = {
    currentQueryContext: new __compactRuntime.QueryContext(chargedState, __compactRuntime.dummyContractAddress()),
    costModel: __compactRuntime.CostModel.initialCostModel()
  };

  const budget = _readCell(context, 0);
  const spent = _readCell(context, 1);
  const counter = _readCell(context, 2);

  return {
    employer_treasury_vk: 0n,
    certified_runway_days: 0n,
    last_attestation_hash: 0n,
    attestation_timestamp: 0n,
    total_solvency_attestations: 0n,
    total_spent: spent,
    total_disbursed: spent,
    total_settled: spent,
    total_advances_disbursed: spent,
    certified_runway_days: spent,
    total_routed_volume: spent,
    spending_limit: budget,
    total_payroll_budget: budget,
    total_vendor_budget: budget,
    active_streams: counter,
    total_solvency_attestations: counter,
    total_compliance_proofs: counter
  };
}

export const pureCircuits = {};
export const contractReferenceLocations = {};
