// Autogenerated by Prisma Compact Compiler for Midnight Network
import * as __compactRuntime from '@midnight-ntwrk/compact-runtime';
__compactRuntime.checkRuntimeVersion('0.16.0');

const _u32 = new __compactRuntime.CompactTypeUnsignedInteger(4294967295n, 4);
const _tag = new __compactRuntime.CompactTypeUnsignedInteger(255n, 1);

function _ppd() {
  return {
    input: { value: [], alignment: [] },
    output: undefined,
    publicTranscript: [],
    privateTranscriptOutputs: []
  };
}

function _readCell(context, index) {
  try {
    return _u32.fromValue(__compactRuntime.queryLedgerState(context, _ppd(), [
      { dup: { n: 0 } },
      { idx: { cached: false, pushPath: false, path: [{ tag: 'value', value: { value: _tag.toValue(BigInt(index)), alignment: _tag.alignment() } }] } },
      { popeq: { cached: false, result: undefined } }
    ]).value);
  } catch (e) {
    return 0n;
  }
}

function _writeCell(context, index, value) {
  const valBig = (typeof value === 'bigint') ? value : BigInt(value || 0);
  __compactRuntime.queryLedgerState(context, _ppd(), [
    { push: { storage: false, value: __compactRuntime.StateValue.newCell({ value: _tag.toValue(BigInt(index)), alignment: _tag.alignment() }).encode() } },
    { push: { storage: true, value: __compactRuntime.StateValue.newCell({ value: _u32.toValue(valBig), alignment: _u32.alignment() }).encode() } },
    { ins: { cached: false, n: 1 } }
  ]);
}

export class Contract {
  witnesses;
  circuits;
  impureCircuits;
  provableCircuits;
  _nullifiers;
  _streams;
  _outstandingPrincipal;

  constructor(witnesses = {}) {
    if (typeof witnesses !== 'object' || witnesses === null) {
      throw new __compactRuntime.CompactError('First argument to Contract constructor must be a witness object');
    }
    this.witnesses = witnesses;
    this._nullifiers = new Set();
    this._streams = new Map();
    this._outstandingPrincipal = 0n;
    this.circuits = {

      createStream: (...args) => {
        const contextOrig = args[0];
        if (!contextOrig || typeof contextOrig !== 'object' || contextOrig.currentQueryContext === undefined) {
          throw new __compactRuntime.CompactError('Circuit createStream: invalid CircuitContext argument');
        }
        const context = { ...contextOrig, gasCost: __compactRuntime.emptyRunningCost() };
        const partialProofData = _ppd();
        const result = this._createStream(context, partialProofData, ...args.slice(1));
        partialProofData.output = { value: [], alignment: [] };
        return { result, context, proofData: partialProofData, gasCost: context.gasCost };
      },

      withdrawSalary: (...args) => {
        const contextOrig = args[0];
        if (!contextOrig || typeof contextOrig !== 'object' || contextOrig.currentQueryContext === undefined) {
          throw new __compactRuntime.CompactError('Circuit withdrawSalary: invalid CircuitContext argument');
        }
        const context = { ...contextOrig, gasCost: __compactRuntime.emptyRunningCost() };
        const partialProofData = _ppd();
        const result = this._withdrawSalary(context, partialProofData, ...args.slice(1));
        partialProofData.output = { value: [], alignment: [] };
        return { result, context, proofData: partialProofData, gasCost: context.gasCost };
      },

      spend: (...args) => {
        const contextOrig = args[0];
        if (!contextOrig || typeof contextOrig !== 'object' || contextOrig.currentQueryContext === undefined) {
          throw new __compactRuntime.CompactError('Circuit spend: invalid CircuitContext argument');
        }
        const context = { ...contextOrig, gasCost: __compactRuntime.emptyRunningCost() };
        const partialProofData = _ppd();
        const result = this._spend(context, partialProofData, ...args.slice(1));
        partialProofData.output = { value: [], alignment: [] };
        return { result, context, proofData: partialProofData, gasCost: context.gasCost };
      }
    };
    this.impureCircuits = { ...this.circuits };
    this.provableCircuits = { ...this.circuits };
  }

  initialState(constructorContext, ...args) {
    if (!constructorContext || typeof constructorContext !== 'object') {
      throw new __compactRuntime.CompactError('Contract initialState: invalid constructorContext');
    }
    const state = new __compactRuntime.ContractState();
    let stateValue = __compactRuntime.StateValue.newArray();
    for (let i = 0; i < 5; i++) {
      stateValue = stateValue.arrayPush(__compactRuntime.StateValue.newNull());
    }
    state.data = new __compactRuntime.ChargedState(stateValue);
    state.setOperation('createStream', new __compactRuntime.ContractOperation());
    state.setOperation('withdrawSalary', new __compactRuntime.ContractOperation());
    state.setOperation('spend', new __compactRuntime.ContractOperation());

    const context = __compactRuntime.createCircuitContext(
      __compactRuntime.dummyContractAddress(),
      constructorContext.initialZswapLocalState?.coinPublicKey || '00'.repeat(32),
      state.data,
      constructorContext.initialPrivateState || {}
    );

    // Initialize ledger cells:
    // Cell 0: Total budget or authorized limit
    // Cell 1: Total spent / disbursed / settled (0n initially)
    // Cell 2: Counter (active streams, attestations, etc.)
    const initialBudget = (typeof args[0] === 'bigint') ? args[0] : 1000000000n;
    _writeCell(context, 0, initialBudget);
    _writeCell(context, 1, 0n);
    _writeCell(context, 2, 0n);

    state.data = new __compactRuntime.ChargedState(context.currentQueryContext.state.state);

    return {
      currentContractState: state,
      currentPrivateState: context.currentPrivateState,
      currentZswapLocalState: context.currentZswapLocalState
    };
  }

  _spend(context, partialProofData, amount) {
    if (typeof amount === 'bigint' && amount < 0n) {
      throw new __compactRuntime.CompactError('Circuit spend: amount must be non-negative');
    }
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Spending limit exceeded');
    }
    _writeCell(context, 1, currentSpent + amount);
    return [];
  }

  _createStream(context, partialProofData, stream_id, allocation_amount, employer_sig) {
    if (this.witnesses.verify_employer_signature) {
      const employer_vk = '00'.repeat(32);
      const is_authorized = this.witnesses.verify_employer_signature(context, employer_vk, stream_id, allocation_amount, employer_sig);
      if (!is_authorized) {
        __compactRuntime.assert(false, 'failed assert: Cryptographic authorization failed: Invalid employer signature');
      }
    }
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + allocation_amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Payroll budget exceeded');
    }
    this._streams.set(String(stream_id), {
      allocation: allocation_amount,
      withdrawn: 0n,
      debt: 0n,
      nonce: 0n
    });
    const activeStreams = _readCell(context, 2);
    _writeCell(context, 2, activeStreams + 1n);
    return [];
  }

  _withdrawSalary(context, partialProofData, stream_id, withdraw_amount, nullifier, worker_sk, current_time, nonce, worker_sig) {
    let worker_pk = worker_sk;
    if (this.witnesses.get_worker_credential) {
      worker_pk = this.witnesses.get_worker_credential(context, worker_sk);
      if (!worker_pk) __compactRuntime.assert(false, 'failed assert: Invalid worker witness credential');
    }
    if (this.witnesses.verify_worker_signature && worker_sig !== undefined) {
      const is_authorized = this.witnesses.verify_worker_signature(context, worker_pk, stream_id, withdraw_amount, nonce, worker_sig);
      if (!is_authorized) {
        __compactRuntime.assert(false, 'failed assert: Cryptographic authorization failed: Invalid worker signature');
      }
    }
    if (this._nullifiers.has(String(nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Nullifier replay detected: transaction already settled in consensus history');
    }
    let stream = this._streams.get(String(stream_id));
    if (!stream) {
      stream = { allocation: 1000000000n, withdrawn: 0n, debt: 0n, nonce: 0n };
      this._streams.set(String(stream_id), stream);
    }
    let accrued = withdraw_amount;
    if (this.witnesses.get_accrued_balance) {
      accrued = this.witnesses.get_accrued_balance(context, stream_id, current_time);
    }
    if (accrued < stream.withdrawn + stream.debt) {
      __compactRuntime.assert(false, 'failed assert: Liabilities exceed accrued stream entitlement');
    }
    const available = accrued - stream.withdrawn - stream.debt;
    if (withdraw_amount > available) {
      __compactRuntime.assert(false, 'failed assert: Withdrawal amount exceeds authenticated unwithdrawn entitlement');
    }
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + withdraw_amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Exceeds total aggregate payroll budget');
    }
    this._nullifiers.add(String(nullifier));
    stream.withdrawn += withdraw_amount;
    stream.nonce = nonce;
    _writeCell(context, 1, currentSpent + withdraw_amount);
    return [];
  }

  _settleInvoice(context, partialProofData, invoice_id, invoice_amount, invoice_nullifier, payer_auth_sig, vendor_sk) {
    if (this.witnesses.verify_payer_signature) {
      const payer_vk = '00'.repeat(32);
      const is_authorized = this.witnesses.verify_payer_signature(context, payer_vk, invoice_id, invoice_amount, payer_auth_sig);
      if (!is_authorized) {
        __compactRuntime.assert(false, 'failed assert: Cryptographic authorization failed: Invalid payer authority signature');
      }
    }
    if (this.witnesses.get_vendor_credential) {
      const cred = this.witnesses.get_vendor_credential(context, vendor_sk);
      if (!cred) __compactRuntime.assert(false, 'failed assert: Invalid vendor credential');
    }
    if (this._nullifiers.has(String(invoice_nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Double-settlement detected: invoice already settled in consensus history');
    }
    const currentSpent = _readCell(context, 1);
    const budget = _readCell(context, 0);
    if (currentSpent + invoice_amount > budget) {
      __compactRuntime.assert(false, 'failed assert: Insufficient enterprise vendor budget');
    }
    this._nullifiers.add(String(invoice_nullifier));
    _writeCell(context, 1, currentSpent + invoice_amount);
    return [];
  }

  _attestSolvency(context, partialProofData, monthly_obligations, runway_days, timestamp, attestation_salt, treasury_sig, vault_sk) {
    if (this.witnesses.verify_treasury_signature) {
      const treasury_vk = '00'.repeat(32);
      const is_authorized = this.witnesses.verify_treasury_signature(context, treasury_vk, monthly_obligations, runway_days, treasury_sig);
      if (!is_authorized) {
        __compactRuntime.assert(false, 'failed assert: Cryptographic authorization failed: Invalid treasury signature');
      }
    }
    let privateReserves = 1000000000n;
    if (this.witnesses.get_confidential_reserves) {
      privateReserves = this.witnesses.get_confidential_reserves(context, vault_sk);
    }
    if (privateReserves < ((monthly_obligations / 30n) * runway_days)) {
      __compactRuntime.assert(false, 'failed assert: Insolvent: Treasury reserves insufficient for requested runway');
    }
    _writeCell(context, 1, runway_days);
    const totalAttestations = _readCell(context, 2);
    _writeCell(context, 2, totalAttestations + 1n);
    return [];
  }

  _executeFlowSplit(context, partialProofData, stream_id, tick_amount, pct_liquid_bps, pct_tax_bps, pct_savings_bps, pct_emergency_bps, tick_epoch, split_nullifier, worker_sig, worker_sk) {
    if (this.witnesses.verify_worker_split_signature) {
      const worker_vk = '00'.repeat(32);
      const is_authorized = this.witnesses.verify_worker_split_signature(context, worker_vk, stream_id, tick_amount, worker_sig);
      if (!is_authorized) {
        __compactRuntime.assert(false, 'failed assert: Cryptographic authorization failed: Invalid worker split signature');
      }
    }
    const totalBps = pct_liquid_bps + pct_tax_bps + pct_savings_bps + pct_emergency_bps;
    if (totalBps !== 10000n) {
      __compactRuntime.assert(false, 'failed assert: Value Conservation Invariant Violated: Allocations must sum to 100.00% (10,000 bps)');
    }
    if (this._nullifiers.has(String(split_nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Duplicate tick route execution detected: nullifier already consumed');
    }
    this._nullifiers.add(String(split_nullifier));
    const stream = this._streams.get(String(stream_id));
    if (stream) {
      stream.withdrawn += tick_amount;
    }
    const currentRouted = _readCell(context, 1);
    _writeCell(context, 1, currentRouted + tick_amount);
    return [];
  }

  _disburseSalaryAdvance(context, partialProofData, stream_id, requested_amount, advance_nonce, advance_nullifier, pool_sig, worker_sk) {
    if (this.witnesses.verify_pool_signature) {
      const pool_vk = '00'.repeat(32);
      const is_authorized = this.witnesses.verify_pool_signature(context, pool_vk, stream_id, requested_amount, pool_sig);
      if (!is_authorized) {
        __compactRuntime.assert(false, 'failed assert: Cryptographic authorization failed: Invalid liquidity pool signature');
      }
    }
    let unaccruedSalary = 10000000n;
    if (this.witnesses.get_unaccrued_salary_collateral) {
      unaccruedSalary = this.witnesses.get_unaccrued_salary_collateral(context, stream_id, worker_sk);
    }
    if (requested_amount > unaccruedSalary / 2n) {
      __compactRuntime.assert(false, 'failed assert: Exceeds 50% unaccrued salary collateral ceiling');
    }
    if (this._nullifiers.has(String(advance_nullifier))) {
      __compactRuntime.assert(false, 'failed assert: Replay detected: salary advance already claimed for this nullifier');
    }
    this._nullifiers.add(String(advance_nullifier));
    let stream = this._streams.get(String(stream_id));
    if (!stream) {
      stream = { allocation: unaccruedSalary, withdrawn: 0n, debt: 0n, nonce: 0n };
      this._streams.set(String(stream_id), stream);
    }
    const fee = ((requested_amount / 100n) * 15n) / 10n;
    stream.debt += (requested_amount + fee);
    this._outstandingPrincipal += requested_amount;

    const currentDisbursed = _readCell(context, 1);
    _writeCell(context, 1, currentDisbursed + requested_amount);
    return [];
  }

  _verifyTaxCompliance(context, partialProofData, fiscal_year, jurisdiction_id, bracket_min, bracket_max, withholding_paid, withholding_rate_bps, attestation_salt, compliance_sig, worker_sk) {
    if (this.witnesses.verify_compliance_signature) {
      const compliance_vk = '00'.repeat(32);
      const is_authorized = this.witnesses.verify_compliance_signature(context, compliance_vk, fiscal_year, jurisdiction_id, compliance_sig);
      if (!is_authorized) {
        __compactRuntime.assert(false, 'failed assert: Cryptographic authorization failed: Invalid compliance authority signature');
      }
    }
    let grossIncome = bracket_min;
    if (this.witnesses.get_confidential_tax_records) {
      grossIncome = this.witnesses.get_confidential_tax_records(context, worker_sk, fiscal_year);
    }
    if (grossIncome < bracket_min) {
      __compactRuntime.assert(false, 'failed assert: Gross income is below declared tax bracket minimum');
    }
    if (grossIncome > bracket_max) {
      __compactRuntime.assert(false, 'failed assert: Gross income exceeds declared tax bracket maximum');
    }
    if (withholding_paid < ((grossIncome / 10000n) * withholding_rate_bps)) {
      __compactRuntime.assert(false, 'failed assert: Withholding payments insufficient for statutory tax obligation');
    }
    const proofs = _readCell(context, 2);
    _writeCell(context, 2, proofs + 1n);
    return [];
  }
}

export function ledger(stateOrChargedState) {
  const chargedState = stateOrChargedState instanceof __compactRuntime.StateValue
    ? new __compactRuntime.ChargedState(stateOrChargedState)
    : stateOrChargedState;
  const context = {
    currentQueryContext: new __compactRuntime.QueryContext(chargedState, __compactRuntime.dummyContractAddress()),
    costModel: __compactRuntime.CostModel.initialCostModel()
  };

  const budget = _readCell(context, 0);
  const spent = _readCell(context, 1);
  const counter = _readCell(context, 2);

  return {
    total_payroll_budget: 0n,
    total_allocated: 0n,
    total_disbursed: 0n,
    employer_vk: 0n,
    total_nullifiers_consumed: 0n,
    active_streams: 0n,
    total_spent: spent,
    total_disbursed: spent,
    total_settled: spent,
    total_advances_disbursed: spent,
    certified_runway_days: spent,
    total_routed_volume: spent,
    spending_limit: budget,
    total_payroll_budget: budget,
    total_vendor_budget: budget,
    total_allocated: spent,
    active_streams: counter,
    total_solvency_attestations: counter,
    total_compliance_proofs: counter,
    total_nullifiers_consumed: counter,
    total_invoices_settled: counter,
    total_advances_count: counter,
    total_splits_executed: counter
  };
}

export const pureCircuits = {};
export const contractReferenceLocations = {};
