// Autogenerated by Prisma Compact Compiler for Midnight Network
import type * as __compactRuntime from '@midnight-ntwrk/compact-runtime';

export type Witnesses<PS> = {
  get_confidential_reserves(context: __compactRuntime.WitnessContext<PS>, vault_sk: Uint8Array | string): bigint;
  compute_attestation_digest(context: __compactRuntime.WitnessContext<PS>, runway_days: bigint, monthly_burn: bigint, salt: Uint8Array | string): Uint8Array | string;
};

export type ImpureCircuits<PS> = {
  attestSolvency(context: __compactRuntime.CircuitContext<PS>, monthly_obligations: bigint, runway_days: bigint, timestamp: bigint, attestation_salt: Uint8Array | string, treasury_sig: Uint8Array | string, vault_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type ProvableCircuits<PS> = {
  attestSolvency(context: __compactRuntime.CircuitContext<PS>, monthly_obligations: bigint, runway_days: bigint, timestamp: bigint, attestation_salt: Uint8Array | string, treasury_sig: Uint8Array | string, vault_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type PureCircuits = {};

export type Circuits<PS> = {
  attestSolvency(context: __compactRuntime.CircuitContext<PS>, monthly_obligations: bigint, runway_days: bigint, timestamp: bigint, attestation_salt: Uint8Array | string, treasury_sig: Uint8Array | string, vault_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type Ledger = {
  readonly employer_treasury_vk: Uint8Array | string;
  readonly certified_runway_days: bigint;
  readonly last_attestation_hash: Uint8Array | string;
  readonly attestation_timestamp: bigint;
  readonly total_solvency_attestations: bigint;
};

export type ContractReferenceLocations = any;
export declare const contractReferenceLocations: ContractReferenceLocations;

export declare class Contract<PS = any, W extends Witnesses<PS> = Witnesses<PS>> {
  witnesses: W;
  circuits: Circuits<PS>;
  impureCircuits: ImpureCircuits<PS>;
  provableCircuits: ProvableCircuits<PS>;
  constructor(witnesses: W);
  initialState(context: __compactRuntime.ConstructorContext<PS>, ...args: any[]): __compactRuntime.ConstructorResult<PS>;
}

export declare function ledger(state: __compactRuntime.StateValue | __compactRuntime.ChargedState): Ledger;
export declare const pureCircuits: PureCircuits;
