// Autogenerated by Prisma Compact Compiler for Midnight Network
import type * as __compactRuntime from '@midnight-ntwrk/compact-runtime';

export type Witnesses<PS> = {
  get_subvault_commitments(context: __compactRuntime.WitnessContext<PS>, worker_sk: Uint8Array | string): Uint8Array | string;
  compute_split_nullifier(context: __compactRuntime.WitnessContext<PS>, stream_id: Uint8Array | string, tick_epoch: bigint, worker_sk: Uint8Array | string): Uint8Array | string;
};

export type ImpureCircuits<PS> = {
  executeFlowSplit(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, tick_amount: bigint, pct_liquid_bps: bigint, pct_tax_bps: bigint, pct_savings_bps: bigint, pct_emergency_bps: bigint, tick_epoch: bigint, split_nullifier: Uint8Array | string, worker_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type ProvableCircuits<PS> = {
  executeFlowSplit(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, tick_amount: bigint, pct_liquid_bps: bigint, pct_tax_bps: bigint, pct_savings_bps: bigint, pct_emergency_bps: bigint, tick_epoch: bigint, split_nullifier: Uint8Array | string, worker_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type PureCircuits = {};

export type Circuits<PS> = {
  executeFlowSplit(context: __compactRuntime.CircuitContext<PS>, stream_id: Uint8Array | string, tick_amount: bigint, pct_liquid_bps: bigint, pct_tax_bps: bigint, pct_savings_bps: bigint, pct_emergency_bps: bigint, tick_epoch: bigint, split_nullifier: Uint8Array | string, worker_sig: Uint8Array | string, worker_sk: Uint8Array | string): __compactRuntime.CircuitResults<PS, []>;
  spend(context: __compactRuntime.CircuitContext<PS>, amount: bigint): __compactRuntime.CircuitResults<PS, []>;
};

export type Ledger = {
  readonly worker_authority_vk: Uint8Array | string;
  readonly total_routed_volume: bigint;
  readonly last_split_nullifier: Uint8Array | string;
  readonly routing_active: bigint;
};

export type ContractReferenceLocations = any;
export declare const contractReferenceLocations: ContractReferenceLocations;

export declare class Contract<PS = any, W extends Witnesses<PS> = Witnesses<PS>> {
  witnesses: W;
  circuits: Circuits<PS>;
  impureCircuits: ImpureCircuits<PS>;
  provableCircuits: ProvableCircuits<PS>;
  constructor(witnesses: W);
  initialState(context: __compactRuntime.ConstructorContext<PS>, ...args: any[]): __compactRuntime.ConstructorResult<PS>;
}

export declare function ledger(state: __compactRuntime.StateValue | __compactRuntime.ChargedState): Ledger;
export declare const pureCircuits: PureCircuits;
